name: test
on: ["push", "pull_request"]
jobs:
  test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/linux
    name: Test
    runs-on: ubuntu-latest
    container:
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Grammar test
        run: make test-grammar
        shell: bash
 